### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by richardk80**
Added ability to filter based on both region and group title. Clickable links added for easier navigation. Added favicon and rewrote the title so people know what the webpage is.

### CODE REVIEW

**Comment by matthuisman** [comment]
thanks for the PR.
Im a bit concerned that we are losing the ability to set multiple regions with a comma separated list and also the ability to set the regions at OS.env level (easy to use with Docker)

Can this be kept?

**Comment by richardk80** [comment]
> thanks for the PR. Im a bit concerned that we are losing the ability to set multiple regions with a comma separated list and also the ability to set the regions at OS.env level (easy to use with Docker)
> 
> Can this be kept?

I can take a look at the code and test to see if it's still able to do that. If not then I can work with it to make sure it does.

> thanks for the PR. Im a bit concerned that we are losing the ability to set multiple regions with a comma separated list and also the ability to set the regions at OS.env level (easy to use with Docker)
> 
> Can this be kept?

I tested it and it wasn't in there but it should be now. You can test it yourself and let me know if it meets your standards. If there's anything that needs to be fixed or tweaked, let me know and I'll look into it

**Comment by matthuisman** [comment]
thank you :)

**Comment by matthuisman** [comment]
made a few changes after this merge. Its now called groups and can also be comma separated for multiple.
New docker image pushed.
thanks

**Comment by stewartcampbell** [comment]
Helpful, thanks.

**Comment by richardk80** [comment]
That's cool. I didn't think of comma separating the groups like the regions

**Pull request merged**
